# .github/workflows/dotnet-api.yml
name: .NET API CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Match your project's version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish API
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-api
        path: ./publish
