# .github/workflows/dotnet-api.yml
name: .NET API CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted #windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish API
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-api
        path: ./publish

    - name: Deploy to Local IIS
      run: |
        $iisPath = "C:\inetpub\wwwroot\CICD_Demo_WebApplication"
        $publishPath = "$(System.DefaultWorkingDirectory)/publish"

        Write-Host "Cleaning existing files in IIS path..."
        if (Test-Path $iisPath) {
          Remove-Item "$iisPath\*" -Recurse -Force
        }

        Write-Host "Copying new published files..."
        Copy-Item "$publishPath\*" $iisPath -Recurse

        Write-Host "Restarting IIS..."
        iisreset
      shell: pwsh
